<?php //if($crumbs && is_array($crumbs)): ?>
<section class="breadcrumbWrap">
  <div class="wrapper">
    <div class="block">
      <ul class="breadcrumb">
      <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li <?php if($_crumbInfo['last']) echo 'class="last"' ?>>
            <?php if($_crumbInfo['link']): ?>
                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->escapeHtml($_crumbInfo['title']) ?>"><?php echo $this->escapeHtml($_crumbInfo['label']) ?></a>
            <?php elseif($_crumbInfo['last']): ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php else: ?>
                <?php echo $this->escapeHtml($_crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
       <?php endforeach; ?>
      </ul>
      <ul class="contactInfo">
        <li>Call Anytime: 18001039825</li>
        <li class="emailImg"><a href="#">Email Anytime</a></li>
      </ul>
    </div>
  </div>
</section>
<?php // endif; ?>