      <div class="footerStripWrap">
         <div class="footerStripTop">
            <div class="wrapper">
               <div class="block">
                  <ul class="stripLinks">
                     <li><a href="#strip1"><span>My Wishlist</span></a></li>
                     <li class="second"><a href="#strip2"><span>Recently viewed</span></a></li>
                     <li class="third"><a href="#strip3"><span>Track Order</span></a></li>
                     <li class="fourth"><a href="#strip4"><span>Top Offers</span></a></li>
                     <li class="fifth"><a href="#strip5"><span>Be in Touch</span></a></li>
                     <li class="sixth"><a href="#strip6"><span>Live Chat</span></a></li>
                  </ul>
                  <a class="downArrow" href="#"></a>
               </div>
            </div>
         </div>
         <div class="footerStripBottom">
            <div class="wrapper">
               <div class="block">
                  <div class="stripContent" id="strip1">
                     <h2>Bio honey gel 1</h2>
                     <p>INR 199.00</p>
                  </div>
                  <div class="stripContent" id="strip2">
                     <h2>Bio honey gel 2</h2>
                     <p>INR 199.00</p>
                  </div>
                  <div class="stripContent" id="strip3">
                     <h2>Bio honey gel 3</h2>
                     <p>INR 199.00</p>
                     <h2>Bio honey gel 1</h2>
                     <p>INR 199.00</p>
                  </div>
                  <div class="stripContent" id="strip4">
                     <h2>Bio honey gel 4</h2>
                     <p>INR 199.00</p>
                  </div>
                  <div class="stripContent" id="strip5">
                     <h2>Bio honey gel 5</h2>
                     <p>INR 199.00</p>
                     <h2>Bio honey gel 1</h2>
                     <p>INR 199.00</p>
                     <h2>Bio honey gel 1</h2>
                     <p>INR 199.00</p>
                  </div>
                  <div class="stripContent" id="strip6">
                     <h2>Bio honey gel 6</h2>
                     <p>INR 199.00</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
