		<div class="wrapper">
			<div class="logoBlock">
				<figure><a href="#"><img src="<?php echo $this->getSkinUrl('images/logo.png'); ?>" alt="" /></a></figure>
			</div>
			<div class="bottomRow">
				<nav>
					<ul class="menu">
						<li>
						<a href="#">Collections<span></span></a>
							<div class="dropwrap level3">
								<div class="dropLink">
									<div class="dropsub">
									<h4><a href="#">Skincare Lines</a></h4>
									<ul>
									<li><a href="#">Biotique Advance</a></li>
									<li><a href="#">Biotique Botanical</a></li>
									</ul>
									</div>
								<div class="dropsub">
								<h4><a href="#">Category</a></h4>
									<ul>
									<li><a href="#">Cleansing</a></li>
									<li><a href="#">Exfoliating</a></li>
									<li><a href="#">Toning</a></li>
									<li><a href="#">Vitalizing</a></li>
									<li><a href="#">Mois turizing</a></li>
									<li><a href="#">Scrubs & Masks</a></li>
									<li><a href="#">Eye & Lip Care</a></li>
									<li><a href="#">Sun Care</a></li>
									</ul>
								</div>
									<div class="dropsub droplast">
										<h4><a href="#">Concerns</a></h4>
										<ul>
											<li><a href="#">Dryness</a></li>
											<li><a href="#">Fairness</a></li>
											<li><a href="#">Aging</a></li>
											<li><a href="#">Oily & Acne</a></li>
											<li><a href="#">Uneven Skin Tone</a></li>
											<li><a href="#">Prevention & Protection</a></li>
											<li><a href="#">Dull Skin</a></li>
										</ul>
									</div>
								</div>
								<div class="dropImgwrap">
									<div class="dropImg left">
										<figure><a href="#"><img src="<?php echo $this->getSkinUrl('images/nav-img.jpg'); ?>" alt="" /></a></figure>
									</div>
									<div class="dropImg">
										<figure><a href="#"><img src="<?php echo $this->getSkinUrl('images/nav-img2.jpg'); ?>" alt="" /></a></figure>
									</div>
								</div>
							</div>
						</li>
						<li><a href="#">Skin</a></li>
						<li><a href="#">Hair</a></li>
						<li><a href="#">Bath & Body</a></li>
						<li><a href="#">Baby</a></li>
						<li><a href="#">Men</a></li>
						<li><a href="#">Skin Consultation</a></li>
						<li><a href="#">Great Gifts</a></li>
						<li><a href="#">What's New</a></li>
						<li><a href="#">About us</a></li>
					</ul>
				</nav>
				<ul class="rightIcon">
					<li><a href="#"><i class="fa fa-search"></i></a></li>
					<li><a href="#"><i class="fa fa-lock"></i></a></li>
				</ul>
			</div>
		</div>