<?php if($this->getCollection()->getSize() && $this->getLastPageNum()>1): ?>
<div class="paginationWrap">
    <ul class="pagination">
    <?php if (!$this->isFirstPage()): ?>
        <li>
            <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo $this->getPreviousPageUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                    <i class="fa fa-chevron-left"></i>
            </a>
        </li>
    <?php endif;?>
    
    <?php if ($this->canShowFirst()): ?>
        <li><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
    <?php endif;?>
    <?php if ($this->canShowPreviousJump()): ?>
        <li class="dot"><a href="#"><i class="fa fa-ellipsis-h"></i></a></li>
    <?php endif;?>

    <?php foreach ($this->getFramePages() as $_page): ?>
        <?php if ($this->isPageCurrent($_page)): ?>
            <li class="select"><a href="#"><?php echo $_page ?></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
        <?php endif;?>
    <?php endforeach;?>

    <?php if ($this->canShowNextJump()): ?>
        <li class="dot"><a href="#"><i class="fa fa-ellipsis-h"></i></a></li>
    <?php endif;?>
    <?php if ($this->canShowLast()): ?>
      <li><a href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
    <?php endif;?>
    <?php if (!$this->isLastPage()): ?>
        <li>
            <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo $this->getNextPageUrl() ?>" title="<?php echo $this->__('Next') ?>">
                <i class="fa fa-chevron-right"></i>
            </a>
        </li>
    <?php endif;?>
    </ul>
  </div>
<?php endif ?>