<div class="topLeft">
					<ul class="toplinks">
						<li><a href="#"><i class="fa fa-plus"></i> Free Shipping*</a></li>
						<li><a href="#"><i class="fa fa-plus"></i> Free Samples Always*</a></li>
						<li><a href="#"><i class="fa fa-plus"></i> Web Exclusive Offers</a></li>
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
					</ul>
</div>
				
				
				
			<!--	<div class="topRight">
					<ul class="toplinks">
						<li>
						<a href="#" id="loginctn"><i class="fa fa-plus"></i> Email Signup</a>

							
							
							<div class="signupWrap">
								<h5>Login</h5>
								<ul class="signupRow">
									<li>
									<label>
									<span>Enter your email:</span>
									<input type="text" name="" value="">                
									</label>
									</li>
									<li>
									<label>
									<span>Password</span>
									<input type="text" name="" value="">                
									</label>
									</li>
									<li>
									<input type="submit" name="" value="SIGN IN">
									</li>
								</ul>
							<p><a href="#">Forgot Your Password?</a></p>
							<a href="#" class="ctn-fb"><i class="fa fa-facebook-official"></i><span>Log in with Facebook</span></a>
							</div>
						</li>
						<li><a href="#"><i class="fa fa-plus"></i> My Account/Register</a></li>
						<li><a href="#"><i class="fa fa-plus"></i> Find a Store</a></li>
					</ul>
				</div>  -->
			