<!DOCTYPE html>
<html lang="en">
   <head>
      <?php echo $this->getChildHtml('head') ?>
   </head>
   <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':''?>>
   <?php echo $this->getChildHtml('after_body_start') ?>
      <header id="header">
      	<?php echo $this->getChildHtml('header') ?>
      </header>
      <?php echo $this->getChildHtml('breadcrumbs') ?>
      <?php if( Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' && Mage::getSingleton('cms/page')->getIdentifier() != 'home') : ?>
           <section class="bodyContainer"> 
             <span class="shadow"></span>
             <div class="wrapper">
               <div class="block">
                 <?php echo $this->getChildHtml('content'); ?>
               </div>
             </div>
           </section>
      <?php else: 
          echo $this->getChildHtml('content');
        endif; ?>
      <?php echo $this->getChildHtml('footer') ?>
      <?php echo $this->getAbsoluteFooter() ?>
      <?php echo $this->getChildHtml('before_body_end') ?>
   </body>
</html>