<!DOCTYPE html>
<html lang="en">
   <head>
      <?php echo $this->getChildHtml('head') ?>
   </head>
   <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':''?>>
   <?php echo $this->getChildHtml('after_body_start') ?>
      <header id="header">
        <?php echo $this->getChildHtml('header') ?>
      </header>
      <?php echo $this->getChildHtml('breadcrumbs') ?>
      <?php echo $this->getChildHtml('innerbanner') ?>

      <section class="bodyContainer">
         <span class="shadow"></span>
         <div class="wrapper">
            <div class="block">
               <div class="containerRight">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
               </div>
                <aside class="containerLeft">
                  <?php echo $this->getChildHtml('right') ?>
               </aside>
            </div>
         </div>
      </section>
      <?php echo $this->getChildHtml('footer') ?>
      <?php echo $this->getAbsoluteFooter() ?>
      <?php echo $this->getChildHtml('before_body_end') ?>
   </body>
</html>
