<!DOCTYPE html>
<html lang="en">
   <head>
      <?php echo $this->getChildHtml('head') ?>
   </head>
   <body>
      <header id="header">
         <div class="topRow">
            <div class="wrapper">
               <div class="topLeft">
                  <ul class="toplinks">
                     <li><a href="#"><i class="fa fa-plus"></i> Free Shipping*</a></li>
                     <li><a href="#"><i class="fa fa-plus"></i> Free Samples Always*</a></li>
                     <li><a href="#"><i class="fa fa-plus"></i> Web Exclusive Offers</a></li>
                     <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                     <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                     <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                  </ul>
               </div>
               <div class="topRight">
                  <ul class="toplinks">
                     <li>
                        <a href="#" id="loginctn"><i class="fa fa-plus"></i> Email Signup</a>
                        <div class="signupWrap">
                           <h5>Login</h5>
                           <ul class="signupRow">
                              <li>
                                 <label>
                                 <span>Enter your email:</span>
                                 <input type="text" name="" value="">                
                                 </label>
                              </li>
                              <li>
                                 <label>
                                 <span>Password</span>
                                 <input type="text" name="" value="">                
                                 </label>
                              </li>
                              <li>
                                 <input type="submit" name="" value="SIGN IN">
                              </li>
                           </ul>
                           <p><a href="#">Forgot Your Password?</a></p>
                           <a href="#" class="ctn-fb"><i class="fa fa-facebook-official"></i><span>Log in with Facebook</span></a>
                        </div>
                     </li>
                     <li><a href="#"><i class="fa fa-plus"></i> My Account/Register</a></li>
                     <li><a href="#"><i class="fa fa-plus"></i> Find a Store</a></li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="wrapper">
            <div class="logoBlock">
               <figure><a href="#"><img src="images/logo.png" alt="" /></a></figure>
            </div>
            <div class="bottomRow">
               <nav>
                  <ul class="menu">
                     <li>
                        <a href="#">Collections<span></span></a>
                        <div class="dropwrap level3">
                           <div class="dropLink">
                              <div class="dropsub">
                                 <h4><a href="#">Skincare Lines</a></h4>
                                 <ul>
                                    <li><a href="#">Biotique Advance</a></li>
                                    <li><a href="#">Biotique Botanical</a></li>
                                 </ul>
                              </div>
                              <div class="dropsub">
                                 <h4><a href="#">Category</a></h4>
                                 <ul>
                                    <li><a href="#">Cleansing</a></li>
                                    <li><a href="#">Exfoliating</a></li>
                                    <li><a href="#">Toning</a></li>
                                    <li><a href="#">Vitalizing</a></li>
                                    <li><a href="#">Mois turizing</a></li>
                                    <li><a href="#">Scrubs & Masks</a></li>
                                    <li><a href="#">Eye & Lip Care</a></li>
                                    <li><a href="#">Sun Care</a></li>
                                 </ul>
                              </div>
                              <div class="dropsub droplast">
                                 <h4><a href="#">Concerns</a></h4>
                                 <ul>
                                    <li><a href="#">Dryness</a></li>
                                    <li><a href="#">Fairness</a></li>
                                    <li><a href="#">Aging</a></li>
                                    <li><a href="#">Oily & Acne</a></li>
                                    <li><a href="#">Uneven Skin Tone</a></li>
                                    <li><a href="#">Prevention & Protection</a></li>
                                    <li><a href="#">Dull Skin</a></li>
                                 </ul>
                              </div>
                           </div>
                           <div class="dropImgwrap">
                              <div class="dropImg left">
                                 <figure><a href="#"><img src="images/nav-img.jpg" alt="" /></a></figure>
                              </div>
                              <div class="dropImg">
                                 <figure><a href="#"><img src="images/nav-img2.jpg" alt="" /></a></figure>
                              </div>
                           </div>
                        </div>
                     </li>
                     <li><a href="#">Skin</a></li>
                     <li><a href="#">Hair</a></li>
                     <li><a href="#">Bath & Body</a></li>
                     <li><a href="#">Baby</a></li>
                     <li><a href="#">Men</a></li>
                     <li><a href="#">Skin Consultation</a></li>
                     <li><a href="#">Great Gifts</a></li>
                     <li><a href="#">What's New</a></li>
                     <li><a href="#">About us</a></li>
                  </ul>
               </nav>
               <ul class="rightIcon">
                  <li><a href="#"><i class="fa fa-search"></i></a></li>
                  <li><a href="#"><i class="fa fa-lock"></i></a></li>
               </ul>
            </div>
         </div>
      </header>
      <section id="slider">
         <div class="flexslider" id="flexslider1">
            <ul class="slides">
               <li>
                  <img src="images/slide_img1.jpg" alt="" />
               </li>
               <li>
                  <img src="images/slide_img2.jpg" alt="" />
               </li>
            </ul>
         </div>
      </section>
      <div class="newCollection">
         <div class="collectionTop">
            <div class="wrapper">
               <h1>our new collection</h1>
            </div>
            <em class="shape"></em>
         </div>
         <div class="collectionBottom">
            <em class="shadow"></em>
            <div class="wrapper">
               <div class="collectionImg">
                  <figure><img src="images/collectionImg.jpg" alt="" /></figure>
               </div>
               <div class="collectionCon">
                  <div class="collectionLeft">
                     <figure><img src="images/biotique.png" alt="" /></figure>
                  </div>
                  <div class="collectionRight">
                     <h2>A window to our exclusive luxury collection</h2>
                     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam.</p>
                     <a href="#" class="ctnBtn">View collection</a>
                     <a href="#" class="ctnBtn">why Biotique advance?</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="bestSellers">
         <em class="shadow"></em>
         <div class="bestSellersbg">
            <figure><img src="images/sellers.jpg" alt="" /></figure>
         </div>
         <div class="bestSellerscon">
            <div class="wrapper">
               <div class="sellersContent">
                  <h3>best sellers</h3>
                  <p>Go head over heels with our 10 most beloved formulations chosen by our customers</p>
               </div>
               <div class="sellersSlider">
                  <div id="bestseller" class="sky-carousel">
                     <div class="sky-carousel-wrapper">
                        <ul class="sky-carousel-container">
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl1img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl2img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel 2</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl3img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel 3</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl4img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel 4</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl5img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel 5</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                           <li>
                              <img src="images/seller2.png" alt="" />
                              <a href="javascript:;" id="sl6img" class="bigImg fancybox"></a>
                              <div class="sc-content">
                                 <h2>Bio honey gel 6</h2>
                                 <p>INR 199.00</p>
                              </div>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="product-feature">
         <section class="wrapper">
            <article class="product-left">
               <figure> <img src="images/girl_pic.png" alt="" title=""> </figure>
               <section class="prod-desc">
                  <h2>SKIN CONSULTATION</h2>
                  <h5>FIND THE BEST SOLUTIONS</h5>
                  <p>Learn more about your skin type and the products that are perfect for you with our Skincare Consultation</p>
                  <a href="#">FIND MORE</a>
               </section>
            </article>
            <article class="product-right">
               <figure>
                  <div class="flexslider" id="flexslider2">
                     <ul class="slides">
                        <li>
                           <img src="images/coconut.png" alt="" title="">
                           <strong>COCONUT</strong>
                           <a href="#" class="read-more">Read More</a>
                        </li>
                        <li>
                           <img src="images/coconut.png" alt="" title="">
                           <strong>COCONUT</strong>
                           <a href="#" class="read-more">Read More</a>
                        </li>
                        <li>
                           <img src="images/coconut.png" alt="" title="">
                           <strong>COCONUT</strong>
                           <a href="#" class="read-more">Read More</a>
                        </li>
                     </ul>
                  </div>
               </figure>
               <section class="prod-desc">
                  <h2>INGREDIENTS</h2>
                  <h5>TAKE THE NATURAL PATH</h5>
                  <p>Biotique blends the powers of Ayurvedic healing wisdom</p>
                  <a href="#">FIND ALL</a>
               </section>
            </article>
         </section>
      </div>
      <!-- end product-feature -->
      <div class="site_info">
         <div class="wrapper">
            <section class="locator">
               <h4>STORE LOCATOR</h4>
               <p>Search Stores using the options below:</p>
               <select class="select_box">
                  <option>Select City</option>
                  <option>Delhi</option>
                  <option>Indore</option>
                  <option>Mumbai</option>
                  <option>Bhopal</option>
               </select>
            </section>
            <section class="testimonials">
               <h4>TESTIMONIALS</h4>
               <section class="item">
                  <div class="flexslider" id="flexslider3">
                     <ul class="slides">
                        <li>
                           <figure class="item_img"> <img src="images/prod_test.png" alt="" title=""> </figure>
                           <section class="item_desc">
                              <h5>BIO SEAWEED</h5>
                              <h6>REVITALIZING ANTI-FATIGUE EYE GEL</h6>
                              <p>I’ve never used a cream so soothing and hydrating to my eyes! I am so in love with Creamy Eye Treatment with Bio Seaweed</p>
                              <strong>- Sarika | Skincare Expert</strong> <a href="#">- View All</a> 
                           </section>
                        </li>
                        <li>
                           <figure class="item_img"> <img src="images/prod_test.png" alt="" title=""> </figure>
                           <section class="item_desc">
                              <h5>BIO SEAWEED</h5>
                              <h6>REVITALIZING ANTI-FATIGUE EYE GEL</h6>
                              <p>I’ve never used a cream so soothing and hydrating to my eyes! I am so in love with Creamy Eye Treatment with Bio Seaweed</p>
                              <strong>- Sarika | Skincare Expert</strong> <a href="#">- View All</a> 
                           </section>
                        </li>
                        <li>
                           <figure class="item_img"> <img src="images/prod_test.png" alt="" title=""> </figure>
                           <section class="item_desc">
                              <h5>BIO SEAWEED</h5>
                              <h6>REVITALIZING ANTI-FATIGUE EYE GEL</h6>
                              <p>I’ve never used a cream so soothing and hydrating to my eyes! I am so in love with Creamy Eye Treatment with Bio Seaweed</p>
                              <strong>- Sarika | Skincare Expert</strong> <a href="#">- View All</a> 
                           </section>
                        </li>
                     </ul>
                  </div>
               </section>
            </section>
            <section class="social_connect">
               <h4>CONNECT WITH US</h4>
               <section class="social_icons">
                  <section class="social_icon_left">
                     <section class="social_icon_right">
                        <section class="social_icon_mid">
                           <ul>
                              <li class="twit">
                                 <a class="twitter" href="javascript:void(0)"></a>
                              </li>
                              <li class="faceb">
                                 <a class="fb" href="javascript:void(0)"></a>
                              </li>
                              <li class="yout">
                                 <a class="yt" href="javascript:void(0)"></a>
                              </li>
                              <li class="blog_">
                                 <a class="blog" href="javascript:void(0)"></a>
                              </li>
                              <li class="pin_">
                                 <a class="pin" href="javascript:void(0)"></a>
                              </li>
                           </ul>
                        </section>
                     </section>
                  </section>
                  <section class="social_content">
                     <section id="twit">
                        <h6>Biotique @Biotique_World </h6>
                        <p>#TipOfTheDay If your eyes look red or tired, your skin will look drab as well. Wake up your peepers with some eye... <a href"">http://fb.me/2CGrPXHqo</a></p>
                     </section>
                     <section id="faceb">
                        <h6>Facebook @Biotique_World </h6>
                        <p>#TipOfTheDay If your eyes look red or tired, your skin will look drab as well. Wake up your peepers with some eye... <a href"">http://fb.me/2CGrPXHqo</a></p>
                     </section>
                     <section id="yout">
                        <h6>YouTube @Biotique_World </h6>
                        <p>#TipOfTheDay If your eyes look red or tired, your skin will look drab as well. Wake up your peepers with some eye... <a href"">http://fb.me/2CGrPXHqo</a></p>
                     </section>
                     <section id="blog_">
                        <h6>Blog @Biotique_World </h6>
                        <p>#TipOfTheDay If your eyes look red or tired, your skin will look drab as well. Wake up your peepers with some eye... <a href"">http://fb.me/2CGrPXHqo</a></p>
                     </section>
                     <section id="pin_">
                        <h6>Pin @Biotique_World </h6>
                        <p>#TipOfTheDay If your eyes look red or tired, your skin will look drab as well. Wake up your peepers with some eye... <a href"">http://fb.me/2CGrPXHqo</a></p>
                     </section>
                  </section>
               </section>
            </section>
         </div>
      </div>
      <div class="footerStripWrap">
         <div class="footerStripTop">
            <div class="wrapper">
               <ul class="stripLinks">
                  <li><a href="#strip1"><span>My Wishlist</span></a></li>
                  <li class="second"><a href="#strip2"><span>Recently viewed</span></a></li>
                  <li class="third"><a href="#strip3"><span>Track Order</span></a></li>
                  <li class="fourth"><a href="#strip4"><span>Top Offers</span></a></li>
                  <li class="fifth"><a href="#strip5"><span>Be in Touch</span></a></li>
                  <li class="sixth"><a href="#strip6"><span>Live Chat</span></a></li>
               </ul>
               <a class="downArrow" href="#"></a>
            </div>
         </div>
         <div class="footerStripBottom">
            <div class="wrapper">
               <div class="stripContent" id="strip1">
                  <h2>Bio honey gel 1</h2>
                  <p>INR 199.00</p>
               </div>
               <div class="stripContent" id="strip2">
                  <h2>Bio honey gel 2</h2>
                  <p>INR 199.00</p>
               </div>
               <div class="stripContent" id="strip3">
                  <h2>Bio honey gel 3</h2>
                  <p>INR 199.00</p>
               </div>
               <div class="stripContent" id="strip4">
                  <h2>Bio honey gel 4</h2>
                  <p>INR 199.00</p>
               </div>
               <div class="stripContent" id="strip5">
                  <h2>Bio honey gel 5</h2>
                  <p>INR 199.00</p>
               </div>
               <div class="stripContent" id="strip6">
                  <h2>Bio honey gel 6</h2>
                  <p>INR 199.00</p>
               </div>
            </div>
         </div>
      </div>
      <footer id="footer">
         <section class="footersection1">
            <div class="wrapper">
               <ul class="footTopLinks">
                  <li class="first"><a href="#">About US</a></li>
                  <li class="second"><a href="#">Beauty blog</a></li>
                  <li class="third"><a href="#">Newsletter</a></li>
                  <li class="fourth"><a href="#">Videos</a></li>
                  <li class="fifth"><a href="#">Hotel & Spa  </a></li>
                  <li class="sixth"><a href="#">Facebook</a></li>
               </ul>
            </div>
         </section>
         <section class="footersection2">
            <div class="wrapper">
               <ul class="bottomLinks">
                  <li>
                     <div class="bottcol">
                        <h3>About Us</h3>
                        <ul class="links">
                           <li><a href="#">Our Mission</a></li>
                           <li><a href="#">Our Heritage</a></li>
                           <li><a href="#">Birth of Brand</a></li>
                           <li><a href="#">Cultivating Experience</a></li>
                           <li><a href="#">Our Ingredients</a></li>
                        </ul>
                     </div>
                  </li>
                  <li class="second">
                     <div class="bottcol">
                        <h3>Customer Service</h3>
                        <ul class="links">
                           <li><a href="#">Toll Free No. 18001039825</a></li>
                           <li><a href="#">FAQ</a></li>
                           <li><a href="#">Contact Us</a></li>
                           <li><a href="#">Return & Exchanges</a></li>
                           <li><a href="#">Store Locator</a></li>
                           <li><a href="#">Sitemap</a></li>
                           <li><a href="#">Privacy Policy</a></li>
                           <li><a href="#">Terms & Conditions</a></li>
                        </ul>
                     </div>
                  </li>
                  <li>
                     <div class="bottcol">
                        <h3>My Account</h3>
                        <ul class="links">
                           <li><a href="#">Login/Signup</a></li>
                           <li><a href="#">Order History</a></li>
                           <li><a href="#">My Wishlist</a></li>
                           <li><a href="#">Change Password</a></li>
                           <li><a href="#">Order Tracking</a></li>
                        </ul>
                     </div>
                  </li>
                  <li>
                     <div class="bottcol">
                        <h3>Products</h3>
                        <ul class="links">
                           <li><a href="#">Skin</a></li>
                           <li><a href="#">Hair</a></li>
                           <li><a href="#">Body</a></li>
                           <li><a href="#">Baby</a></li>
                           <li><a href="#">Men</a></li>
                           <li><a href="#">Great Gifts</a></li>
                           <li><a href="#">Testimonial</a></li>
                        </ul>
                     </div>
                  </li>
                  <li>
                     <div class="bottcol">
                        <h3>Corporate</h3>
                        <ul class="links">
                           <li><a href="#">Corporate Gifting</a></li>
                           <li><a href="#">Corporate Events</a></li>
                           <li><a href="#">Hotel & Spa</a></li>
                           <li><a href="#">Press & News</a></li>
                           <li><a href="#">Careers</a></li>
                        </ul>
                     </div>
                  </li>
                  <li class="last">
                     <div class="bottcol">
                        <h3>Social Media</h3>
                        <ul class="socialLinks">
                           <li><a href="#">Facebook</a></li>
                           <li class="second"><a href="#">Google +</a></li>
                           <li class="third"><a href="#">Twitter</a></li>
                           <li class="fourth"><a href="#">Youtube</a></li>
                           <li class="fifth"><a href="#">Pinterest</a></li>
                           <li class="sixth"><a href="#">Instagram</a></li>
                           <li class="seven"><a href="#">Blog</a></li>
                        </ul>
                     </div>
                  </li>
               </ul>
               <p>Worldwide Copyright © Bio Veda Action Research Co. (brand owners of Biotique). All rights reserved.</p>
            </div>
         </section>
         <section class="secureSec">
            <div class="wrapper">
               <div class="secureShop">
                  <h4>Secure shopping :</h4>
                  <figure class="secureImg"><img src="images/secure_Img.jpg" alt="" /></figure>
               </div>
               <div class="paymentSec">
                  <h4>Payment options :</h4>
                  <ul class="paymentImg">
                     <li>
                        <figure><img src="images/payImg1.jpg" alt="" /></figure>
                     </li>
                     <li>
                        <figure><img src="images/payImg2.jpg" alt="" /></figure>
                     </li>
                     <li>
                        <figure><img src="images/payImg3.jpg" alt="" /></figure>
                     </li>
                     <li>
                        <figure><img src="images/payImg4.jpg" alt="" /></figure>
                     </li>
                  </ul>
               </div>
               <div class="shippingSec">
                  <h4>Shipping Partners :</h4>
                  <ul class="shippingImg">
                     <li>
                        <figure><img src="images/shippingImg1.jpg" alt="" /></figure>
                     </li>
                     <li>
                        <figure><img src="images/shippingImg2.jpg" alt="" /></figure>
                     </li>
                     <li>
                        <figure><img src="images/shippingImg3.jpg" alt="" /></figure>
                     </li>
                  </ul>
               </div>
            </div>
         </section>
         <section class="productSec">
            <div class="wrapper">
               <h4>Our Products</h4>
               <p>BIOTIQUE is synonymous with serious skin and hair care developed from Ayurveda. Biotique treatments do not cover up problems - they eliminate them. With 100% natural botanicals. No chemicals. No preservatives. No animal testing. Even the packaging is eco-friendly and recyclable.</p>
            </div>
         </section>
      </footer>
   </body>
</html>