 <?php 
		$recommended="0";
		$read = Mage::getSingleton('core/resource')->getConnection('core_read');
		$reviewsCount = Mage::getModel('review/review')->getTotalReviews($this->getProduct()->getId(), true, Mage::app()->getStore()->getId());
		$result_final = $read->fetchAll("SELECT * FROM review_detail LEFT JOIN review ON review_detail.review_id=review.review_id where review.entity_pk_value = '".$this->getProduct()->getId()."' AND review.status_id=1 AND review_detail.recommend=1"); 
		$val=(count($result_final)/$this->getReviewsCount())*100;
		if($this->getRequest()->getControllerName()=='product') { ?>
		
<?php $category_id = Mage::registry('current_category')->getId();?>		
<div class="star"> <span style="width:<?php echo $this->getRatingSummary() ?>%;"></span> </div>
          <p><?php echo count($result_final)." of ".$reviewsCount." (".number_format($val,2)."%)" ?> reviewers would recommend this product</p>
         
		 <ul class="reviewLink">
            <li <?php if($category_id == 116 || $category_id == 141){?> class="right-review_purple" <?php } else { ?> class="right-review" <?php }?>><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><i class="fa fa-pencil"></i>Write a Review</a></li>
            <li <?php if($category_id == 116 || $category_id == 141){?> class="read-review_purple" <?php } else { ?> class="read-review" <?php }?>><a href="<?php echo $this->getReviewsUrl() ?>">Read All Reviews</a></li>
            <li class="share">Share :</li>
			<!-- <a href="javascript:popWin('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($productUrl); ?>&t=<?php echo urlencode($productName); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Share on Facebook') ?>">Facebook</a>
								<a href="javascript:popWin('http://twitter.com/home/?status=<?php echo urlencode($productName . ' (' . $productUrl . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Tweet') ?>">Twitter</a>
								<a href="javascript:popWin('https://pinterest.com/pin/create/button/?url=<?php echo urlencode($productUrl); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($productName); ?>', 'pinterest', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Pin it') ?>">Pinterest</a> -->

            <li class="tw"><a href="javascript:popWin('http://twitter.com/home/?status=<?php echo urlencode($productName . ' (' . $productUrl . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Tweet') ?>"><i class="fa fa-twitter"></i></a></li>
            <li class="fb"><a href="javascript:popWin('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($productUrl); ?>&t=<?php echo urlencode($productName); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Share on Facebook') ?>"><i class="fa fa-facebook"></i></a></li>
            <li class="pint"><a href="javascript:popWin('https://pinterest.com/pin/create/button/?url=<?php echo urlencode($productUrl); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($productName); ?>', 'pinterest', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo $this->__('Pin it') ?>"><i class="fa fa-pinterest-p"></i></a></li>
          </ul>
		   <?php }
else{
?>
	 <div class="review">
                              <div class="star"> <span style="width:<?php echo $this->getRatingSummary() ?>%;"></span> </div>
                              <span class="review-text">(<?php echo $reviewsCount ?> reviews)</span> </div>

	<?php } ?>

