<?php echo 'sdfds'; die; ?>
<div class="layout"> 
      <span class="shadow"></span>
      <div class="shoppingbagContainer">
        <ul class="shoppingBag">
          <li><span class="sCircle">1</span><span class="shoppingText">Shopping Bag</span></li>
          <li><span class="sCircle active">2</span><span class="shoppingText activeText">Gift and sample</span></li>
          <li><span class="sCircle">3</span><span class="shoppingText">Shipping and Payment</span></li>
          <li><span class="sCircle">4</span><span class="shoppingText">Order review</span></li>
        </ul>
         <span class="shoppingShadow"></span>
      </div>
   <div class="shoppingdetailsArea samplingWrap">
    <div class="shoppingareaLeft">
          <div class="shadowtop">
            <div class="shadowBottom">              
              <div class="sapmlingLine">
                <p class="smaplingText">Congratulations!! You have been entitiled to choose 2 Samples from the below collection Shop for INR 500 amount more and get TWO FREE Sample</p>
              </div> 
              <div class="samplingProduct">
                <ul class="giftProduct">
                  <li>
                    <div class="giftproductList">
                      <figure>
                        <img src="images/gift-pro1.png"/>
                      </figure>
                      <div class="giftDetails">
                        <input type="checkbox" class="styled" name="" value="" >
                        <span class="giftHeading">Bio Apricot</span>
                        <span class="giftText">Refershing </span>
                        <span class="giftText">Body Wash</span>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="giftproductList">
                      <figure>
                        <img src="images/gift-pro1.png"/>
                      </figure>
                      <div class="giftDetails">
                        <input type="checkbox" class="styled" name="" value="" >
                        <span class="giftHeading">Bio GReen Apple</span>
                        <span class="giftText">Fresh Daily Purifying </span>
                        <span class="giftText">Shampoo</span>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="giftproductList">
                      <figure>
                        <img src="images/gift-pro1.png"/>
                      </figure>
                      <div class="giftDetails">
                        <input type="checkbox" class="styled" name="" value="" >
                        <span class="giftHeading">Bio Watercress</span>
                        <span class="giftText">Fresh Nourishing </span>
                        <span class="giftText">Conditioner</span>
                      </div>
                    </div>
                  </li>

                  <li>
                    <div class="giftproductList">
                      <figure>
                        <img src="images/gift-pro1.png"/>
                      </figure>
                      <div class="giftDetails">
                        <input type="checkbox" class="styled" name="" value="" >
                        <span class="giftHeading">Bio Morining Nector</span>
                        <span class="giftText">Flawless Skin</span>
                        <span class="giftText">Lotion</span>
                      </div>
                    </div>
                  </li>
                </ul>               
              </div>              
              <a href="#" class="continueShopping"><i class="fa fa-backward"></i>Continue Shopping</a>              
            </div>
          </div>
        </div>
   <div class="shoppingareaRight">
      <div class="applyCupon">
      <?php echo $this->getChildHtml('checkout.cart.extra') ?>
      
         <?php echo $this->getChildHtml('coupon') ?>
         <!--<span class="shippingTax">Estimate Shipping and Tax</span>
         <span class="destination">Enter your destination to get a shipping estimate.</span>-->
         <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
         <!--<div class="codeApply">
            <input type="text" value="Enter your Zip/Postal Code*" name="code1"/>
            <a href="#" class="applyBtn">apply</a>
         </div>-->
      </div>
      <div class="bagSummary">
         <h4>shopping bag summary</h4>
      </div>
      <div class="sINR">
         <?php echo $this->getChildHtml('totals'); ?>
         <?php if(!$this->hasError()): ?>
            <a href="<?php echo Mage::getBaseUrl(); ?>checkout/onepage" class="checkout"><i class="fa fa-chevron-right"></i>choose sample and checkout</a> 
         <?php endif; ?>
      </div>
      <div class="secure">
         <ul class="risk">
            <li class="riskIcon">                
               <span class="shop">Zero</span>
               <span class="buy">Risk Buy</span>
            </li>
            <li class="shopIcon">                
               <span class="shop">Shop</span>
               <span class="buy">Safe & Secure</span>
            </li>
            <li class="shopwithIcon">                
               <span class="shop">Shop with</span>
               <span class="buy">confidence</span>
            </li>
         </ul>
      </div>
   </div>
</div>
</div>