<div class="spaEnquiryForm">
	<div class="layout">
		<h4>Enquiry</h4>
		<p>We invite you to treat your guests to natural and authentic Biotique products. Please submit the form below and a Biotique representative will respond promptly to your inquiry.</p>
		<form method="post" action="settings/index/hotelspa" >
			<ul class="spaenquiryrow">
				<li><input type="text" value="Hotel Name *" name="hotel_name" /></li>
				<li><input type="text" value="Contact Person Name *" name="person_name" /></li>
				<li><input type="text" value="No. of Hotels *" name="no_hotels" /></li>
				<li><input type="text" value="Designation *" name="designation" /></li>
				<li><input type="text" value="No. of Guest Rooms *" name="no_rooms" /></li>
				<li><input type="text" value="Contact No. *" name="contact_no" /></li>
				<li><input type="text" value="Current Brand for Room Amenties" name="brand" /></li>
				<li><input type="text" value="Email Address *" name="email" /></li>
				<li><input type="text" value="Average Room Occupany/Year(in %)" name="occupancy" /></li>
				<li><input type="text" value="Website" name="website" /></li>
				<li><textarea name="query" rows="5" cols="0">Query</textarea></li>
				<li><textarea name="address" rows="5" cols="0">Address *</textarea></li>
				<li class="last"> <input type="submit" value="SUBMIT" name="submit" /> </li>
			</ul>
		</form>
	</div>
</div>