<?php
echo $attribute_id = $this->getRequest()->getParam('ingre');
$_productCollection = Mage::getResourceModel('catalog/product_collection');
$_productCollection->addAttributeToSelect('name','item_ingregident');
$_productCollection->addAttributeToFilter('item_ingregident', array('eq' => $attribute_id));

if(!$_productCollection->count()){ ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php }else{
	echo "working";
} ?>