<?php
$ingredient_id = $this->getRequest()->getParam('item_ingregident');
$cat= $this->getRequest()->getParam('cat');
$item_concern= $this->getRequest()->getParam('item_concern');
$item_collection= $this->getRequest()->getParam('item_collection');
if($ingredient_id && !$cat && !$item_collection && !$item_concern){

$_helper = $this->helper('catalog/output');
$cat_id=$this->getLayer()->getCurrentCategory()->getId(); 
$innerProduct=Mage::helper('banner')->inner_product($cat_id);
$page='1';
$page=$this->getRequest()->getParam('p');

if(isset($innerProduct[0]['image']) && $innerProduct[0]['image'] != ''){
	$image_path=Mage::getBaseUrl('media') . 'banners/' . $innerProduct[0]['image'];
}
$sr=0;
$productIds=array();
$_productCollection=Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*');
$_productCollection->addAttributeToFilter('visibility', array('in' => array(2,4) ));
$_productCollection-> addAttributeToFilter('status', array('in' => array(1) ));
//Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($_productCollection);
foreach ($_productCollection as $_product){		
		$product_coll = $_product->getData(); $ingredient_collection = $product_coll['item_ingregident']; 	//print_r($product_coll);
		if (strpos($ingredient_collection,$ingredient_id) !== false) {
		$productIds[]=$_product->getId();
		}
}
$totalcount=Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*')->addAttributeToFilter('entity_id', array('in' => $productIds));
if($totalcount->count()>20)
$pages=($totalcount->count()/20); else $pages='';
if($pages>1)
Mage::getSingleton('core/session')->settotalpage($pages);
else Mage::getSingleton('core/session')->settotalpage(0);
$_productCollection=Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*')->addAttributeToFilter('entity_id', array('in' => $productIds));

$_productCollection->setPageSize(20)->setCurPage($page);

if(!$_productCollection->count()){ ?>
	<!-- <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>-->
<?php }else{ 

	 echo $this->getToolbarHtml() ?>
		<div class="productWrap">
		<?php 
		$_columnCount = $this->getColumnCount(); 
		$i=0; foreach ($_productCollection as $_product){		
		
		 $sr++;
		$_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

		<?php if($i%2 == 0){ ?>
			<div class="productRow">
				<ul class="productBox">
		<?php } ?>
		<?php if($i == 3 && (isset($image_path) && $image_path != '') && ($page == '' || $page == '1')){ ?>
			<li class="last special-pro">
			<div class="probox">
				<div class="proImg">
					<figure><a href= "<?php echo $innerProduct[0]['subtitle'] ?>" target="_blank"><img src="<?php echo $image_path ?>" alt="" /></a></figure>
				</div>
			</div>
		<?php } else{ ?>
			<li <?php echo $i%2 != 0 ? ' class="last"':''; ?> >
				<?php $new_prod=$_product->getData('new_product');//To check if product is set new ?>		  		  
					<div class="probox">
							<div class="proImg">
								<figure><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210,290); ?>" width="210" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></figure>
							</div>
							<div <?php if($cat_id == 116 || $cat_id == 141){?> class="proContent_purple" <?php } else { ?> class="proContent" <?php }?>>
									<h4><?php echo $_productNameStripped; ?></h4>
									<p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
									<!-- <small>Best For All Skin Types</small> -->
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
									<h5><?php echo $this->getPriceHtml($_product, true) ?></h5>
									<?php if($_product->isSaleable()): ?>
									<a class="ctn" href="<?php echo $_product->getProductUrl() ?>">shop now</a>

									<!--Added by A on 18-02-2016 for Add to Bag Button -->
									<div class="add2bag_list">
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>">
										<?php if(!$_product->isGrouped()): ?>
										<input type="hidden" name="qty" id="qty" maxlength="3" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>"/>
										<?php endif; ?>
										
										<button class="ctn ctn_BagBtn" onclick="this.form.submit()" title="<?php echo $this->__('Add to bag') ?>"><?php echo $this->__('Add to Bag') ?></button>
										</form>
									</div>
									<!--END Add to Bag Button -->

									<?php else: ?>
									<a href="javascript:void(0)" title="<?php echo $this->__('Sold Out') ?>" class="sold-out"></a>
									<?php endif; ?>
							</div>
					</div>
				<?php } ?>
			</li>
		<?php if($i+1 == sizeof($_productCollection) && $i%2 == 0){ ?>
			<li class="last"></li>
		<?php } ?>
			<?php if($i%2 != 0){ ?>
			</ul>
			<?php } $i++;
			 } //echo 'products='.$sr; ?>
		</div>
	<?php } ?>
	<?php if($sr==0) { ?><p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p><?php } ?>
	 <script>$(".showingProduct span" ).html("<?php echo'showing '.$sr.' product(s)'; ?>");</script>
<?php } else { ?>
<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$cat_id=$this->getLayer()->getCurrentCategory()->getId(); 
$innerProduct=Mage::helper('banner')->inner_product($cat_id);
$page='';
$page=$this->getRequest()->getParam('p'); // output is 1795
if(isset($innerProduct[0]['image']) && $innerProduct[0]['image'] != ''){
	$image_path=Mage::getBaseUrl('media') . 'banners/' . $innerProduct[0]['image'];
}
if(!$_productCollection->count()){ ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php }else{ ?>
	<?php echo $this->getToolbarHtml() ?>
		<div class="productWrap">
		<?php 
		$_columnCount = $this->getColumnCount(); 
		$i=0; foreach ($_productCollection as $_product){
		$_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

		<?php if($i%2 == 0){ ?>
			<div class="productRow">
				<ul class="productBox">
		<?php } ?>
		<?php if($i == 3 && (isset($image_path) && $image_path != '') && ($page == '' || $page == '1')){ ?>
			<li class="last special-pro">
			<div class="probox">
				<div class="proImg">
					<figure><a href= "<?php echo $innerProduct[0]['subtitle'] ?>" target="_blank"><img src="<?php echo $image_path ?>" alt="" /></a></figure>
				</div>
			</div>
		<?php } else{ ?>
			<li <?php echo $i%2 != 0 ? ' class="last"':''; ?> >
				<?php $new_prod=$_product->getData('new_product');//To check if product is set new ?>		  		  
					<div class="probox">
							<div class="proImg">
								<figure><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210,290); ?>" width="210" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></figure>
							</div>
							<div <?php if($cat_id == 116 || $cat_id == 141){?> class="proContent_purple" <?php } else { ?> class="proContent" <?php }?>>
									<h4><?php echo $_productNameStripped; ?></h4>
									<p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
									<!-- <small>Best For All Skin Types</small> -->
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
									<h5><?php echo $this->getPriceHtml($_product, true) ?></h5>
									<?php if($_product->isSaleable()): ?>
									<a class="ctn" href="<?php echo $_product->getProductUrl() ?>">shop now</a>

									<!--Added by A on 18-02-2016 for Add to Bag Button -->
									<div class="add2bag_list">
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>">
										<?php if(!$_product->isGrouped()): ?>
											<input type="hidden" name="qty" id="qty" maxlength="3" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>"/>
											<?php endif; ?>
											
											<button class="ctn ctn_BagBtn" onclick="this.form.submit()" title="<?php echo $this->__('Add to bag') ?>"><?php echo $this->__('Add to Bag') ?></button>
										</form>
									</div>
									<!--END Add to Bag Button -->

									<?php else: ?>
									<a href="javascript:void(0)" title="<?php echo $this->__('Sold Out') ?>" class="sold-out"></a>
									<?php endif; ?>
							</div>
					</div>
				<?php } ?>
			</li>
		<?php if($i+1 == sizeof($_productCollection) && $i%2 == 0){ ?>
			<li class="last"></li>
		<?php } ?>
			<?php if($i%2 != 0){ ?>
			</ul>
			<?php } $i++; } ?>
		</div>
	<?php } ?>

<?php } ?>