<?php
/**
* Product list template
*
* @see Mage_Catalog_Block_Product_List
*/
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$cat_id=$this->getLayer()->getCurrentCategory()->getId(); 
$innerProduct=Mage::helper('banner')->inner_product($cat_id);
$page='';
$page=$this->getRequest()->getParam('p'); // output is 1795
if(isset($innerProduct[0]['image']) && $innerProduct[0]['image'] != ''){
$image_path=Mage::getBaseUrl('media') . 'banners/' . $innerProduct[0]['image'];
}
if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: 
echo $this->getToolbarHtml() ?>
<div class="productWrap">
<?php 
$_columnCount = $this->getColumnCount(); 
$i=0; foreach ($_productCollection as $_product):
$_productNameStripped = $this->stripTags($_product->getName(), null, true); 
    if($i%2 == 0): 
	?>
		<div class="productRow">
			<ul class="productBox">
			<?php endif; ?>
                    <?php 
					if($i == 3 && (isset($image_path) && $image_path != '') && ($page == '' || $page == '1')){
					?>
					<li class="last special-pro">
					<div class="probox">
						<div class="proImg">
							<figure><a href= "<?php echo $innerProduct[0]['subtitle'] ?>" target="_blank"><img src="<?php echo $image_path ?>" alt="" /></a></figure>
						</div>
					</div>
					<?php
					}
					else{
					?>
					<li <?php echo $i%2 != 0 ? ' class="last"':''; ?>>
					<?php
					$new_prod=$_product->getData('new_product');//To check if product is set new ?>		  		  
					<div class="probox">
							<div class="proImg">
								<figure><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210,290); ?>" width="210" height="290" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></figure>
							</div>
							<div class="proContent">
									<h4><?php echo $_productNameStripped; ?></h4>
									<p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
									<small>Best for For All Skin Types</small>
									<?php echo $this->getReviewsSummaryHtml($_product) ?>
									<h5><?php echo $this->getPriceHtml($_product, true) ?></h5>
									<?php if($_product->isSaleable()): ?>
									<a href="<?php echo $_product->getProductUrl() ?>" class="ctn">shop now</a>
									<?php else: ?>
									<a href="javascript:void(0)" title="<?php echo $this->__('Sold Out') ?>" class="sold-out"></a>
									<?php endif; ?>
							</div>
					</div>
			    <?php	} ?>
				</li>
				<?php if($i+1 == sizeof($_productCollection) && $i%2 == 0){ ?>
				<li class="last"></li>
				<?php } ?>
				<?php if($i%2 != 0): ?>
			</ul>
				<?php endif;
				$i++;
         		endforeach ?>
		</div>
<?php endif; ?>