<div class="onepagecheckout opc<?php echo $cssClassShippingAsBilling . $cssClassNoShipping; ?>" id="checkoutSteps">

    <div id="top-links">
        <?php if (!$this->isCustomerLoggedIn()): ?>
        <div id="login-link"><a href="javascript:;" onclick="popupLogin();return false;"><?php echo $this->__('Already registered? Please login here') ?></a></div>
        <?php endif; ?>
        <div id="cart-link">
            <p class="f-right"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        </div>
        <div class="clear"></div>
    </div>

    <div class="column-one border-right">
        <div id="opc-billing" class="section active">
            <div class="step-title">
                <span class="number"></span>
                <h2><?php echo $steps['billing']['label']; ?></h2>
            </div>
            <div id="checkout-step-billing" class="step a-item">
                <?php echo $this->getChildHtml('billing'); ?>
            </div>
        </div>

        <?php if ($canShip) : ?>

        <div id="opc-shipping" class="section active"<?php echo $styleShipping; ?>>
            <div class="step-title">
                <span class="number"></span>
                <h2><?php echo $steps['shipping']['label']; ?></h2>
            </div>
            <div id="checkout-step-shipping" class="step a-item">
                <?php echo $this->getChildHtml('shipping'); ?>
            </div>
        </div>

        <?php endif; ?>
        <div class="clear"></div>
    </div>
    <div class="columns-wrap">
        <div class="column-two border-right">
            <?php if ($canShip) : ?>

            <div id="opc-shipping_method" class="section active">
                <div class="step-title">
                    <span class="number"></span>
                    <h2><?php echo $steps['shipping_method']['label']; ?></h2>
                </div>
                <div id="checkout-step-shipping_method" class="step a-item">
                    <?php echo $this->getChildHtml('shipping_method'); ?>
                </div>
            </div>

            <?php endif; ?>
            <div id="opc-payment" class="section active">
                <div class="step-title">
                    <span class="number"></span>
                    <h2><?php echo $steps['payment']['label']; ?></h2>
                </div>
                <div id="checkout-step-payment" class="step a-item">
                    <?php echo $this->getChildHtml('payment'); ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="column-three">
            <div id="opc-review" class="section active">
                <div class="step-title">
                    <span class="number"></span>
                    <h2><?php echo $steps['review']['label']; ?></h2>
                </div>
                <div id="checkout-step-review" class="step a-item">
                    <?php echo $this->getChildHtml('review'); ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div id="checkout-items-after">
            <?php echo $this->getChildHtml('items_after'); ?>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>
