<div id="newsletter-subscription-wrap" class="checkout-agreements">
    <div class="newsletter-subscription">
        <p>
            <input type="checkbox" name="is_subscribed" id="is_subscribed" value="1" class="checkbox"<?php echo $this->getCheckedStatus(); ?>/>
            <label for="is_subscribed"><?php echo Mage::helper('customer')->__('Sign Up for Newsletter') ?></label>
        </p>
    </div>
</div>
