<script type="text/javascript">
jQuery(document).ready(function(){
               		jQuery("#inTouch").validate({
                rules: {
                    email_id: {
                        required: true,
						email:true
                    },
					 mobile_no: {
                        required: true,
                        number: true
                    },
					 address: {
                        required: true
                    }
                },
                messages: {
				 email_id: {
                        required: "Email required",
                    },
					mobile_no: {
                        required: "Mobile No. of is required",
                    },
					address: {
                        required: "Address is required",
                    }
				},
				highlight: function(element) {
	               jQuery(element).addClass("error");
	         },
	         unhighlight: function(element) {
	           
	               jQuery(element).removeClass("error");
	         },
	         errorPlacement: function(error, element) {
	            
	               error.insertAfter(element);
	           
	         },
                submitHandler: function(form) {
                    jQuery.ajax({
                        type: "POST",
                        url: "<?php echo $this->getUrl('form-simplecontact/') ?>index/inTouch",
                        data: jQuery(form).serialize(),
                        cache: false,
                        success: function(result) 
						{
                            if (result == '1')
							{
								jQuery("#inTouch")[0].reset();
								jQuery('#error').hide();
                                jQuery("#success").show().delay(5000).fadeOut();
							}
							else
							{
								jQuery("#inTouch")[0].reset();
								jQuery("#error").show().delay(5000).fadeOut();
								jQuery('#success').hide();
							} 
						}
                    });
                    return false;
                }
            });
 //Enquiry form validation ends 			
        }); 
</script>

<div class="footerStripWrap">
    <div class="footerStripTop">
      <div class="layout">        
        <ul class="stripLinks">
          <li class="first"><a href="<?php echo Mage::getUrl("storelocator")?>"><span>Find a store</span></a></li>
          <li class="second"><a href="#strip2"><span>Recently viewed</span></a></li>
          <li class="third"><a href="#strip3"><span>Track Order</span></a></li>
          <li class="fourth"><a href="#strip4"><span>Top Offers</span></a></li>
		  
		  <?php	$customer = Mage::getSingleton('customer/session')->getCustomer();
						if ($customer->getId()){ ?>
		  
           <li class="seven"><a href="#strip7"><span>My Wishlist</span></a></li>
		 <?php  } else { ?> 
		 <li class="seven"><a href="#" id="show_login"><span>My Wishlist</span></a></li>
		 <?php } ?>
          <li class="fifth"><a href="#strip5"><span>Be in Touch</span></a></li>
          <!--<li class="sixth"><a href="#"><span>Live Chat</span></a></li>-->
        </ul>
        <a class="downArrow" href="#"></a>        
      </div>
    </div>
    <div class="footerStripBottom">
      <div class="layout">
        <div class="stripContent" id="strip1">
          <div class="recentlyViewed">
            <em class="shadow-hide"></em>           
			<?php echo $this->getLayout()->createBlock('trackorder/trackorder')->setTemplate('trackorder/trackorder.phtml')->toHtml();?>
			           
          </div>          
        </div>

	  
        <div class="stripContent" id="strip2">
          <div class="recentlyViewed">
            <em class="shadow-hide"></em>
            <div id="recentViewedList">
			<?php $recent_view_item = $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/recently_viewed.phtml')->toHtml();
			if( !empty($recent_view_item) ){
          		echo $recent_view_item;
          	}else{
        	?>
      		<div class="no_Product"><?php echo "No Items Viewed"; ?></div>
      	 	<?php } ?>
            </div>
          </div>          
        </div>
        <div class="stripContent" id="strip3">
          <?php echo $this->getLayout()->createBlock('trackorder/trackorder')->setTemplate('trackorder/trackorder.phtml')->toHtml();?>
        </div>
        <div class="stripContent" id="strip4">
          <div class="topOffers">
            <em class="shadow-hide"></em>
            <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-offers')->toHtml(); ?>

                  <div class="slidercolm">
                    <ul class="productSlider">
					<?php echo $this->getLayout()->createBlock('catalog/product')->setTemplate('catalog/product/skincare_offer.phtml')->toHtml(); ?> 
					</ul>
				  </div>
                  
          </div>
        </div>
        <div class="stripContent" id="strip5">
          <div class="beInTouch">
            <div class="beInTouchLeft">
              <h4>YOUR QUERY/FEEDBACK IS VALUABLE TO US</h4>
			  <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('contacts/form.phtml')->toHtml();?>
            </div>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('be-in-touch')->toHtml(); ?>
          </div>
        </div>
		<div class="stripContent" id="strip7">
		<div class="recentlyViewed">
					<em class="shadow-hide"></em>
					<div id="wishList">
						<?php	$customer = Mage::getSingleton('customer/session')->getCustomer();
						if ($customer->getId())
						{
						$wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true);
						$wishListItemCollection = $wishlist->getItemCollection(); 
							foreach ($wishListItemCollection as $item)
							{
							$Products_one = Mage::getModel('catalog/product')->load($item->getProductId());
							?>
							<div class="item">
								<div class="probox">
									<div class="proImg">
										<?php  if ($item->getId())
										{ ?>
										<figure><img src="<?php echo $Products_one->getImageUrl(); ?>" alt=""></figure>
										<?php 
										} ?>                 
									</div>
									<div class="proContent">
									<!-- <span class="top-hd">Top Seller</span> -->
									<!--<h4><?php echo $item->getName() ?></h4>-->
									<h4><?php echo  $item->getProduct()->getData('name')?></h4>
									<p>  <?php echo ($this->escapeHtml($item->getDescription() ? $item->getDescription() : '')) ?>
									</p>                      
										<!--<div class="review">
											<div class="star">
											<span style="width:60%;"></span>
											</div>
											<span class="review-text">(13 reviews)</span>
										</div> -->
									<!--<h5>₹<?php echo $item->getPrice(); ?></h5>-->
								<!--<h5>₹<?php echo $item->getProduct()->getData('price')?></h5>-->
									<h5><?php echo Mage::helper('core')->currency($item->getProduct()->getMinimalPrice()) ?></h5>
									<a href="<?php echo $this->getProductUrl($item); ?>" class="ctn">shop now</a> 
									</div>
								</div>
							</div>
							<?php 
							} 
						} else {?>
							<!--<h1 style="text-align:center; color:red;">Please login to Continue!</h1>--->
						<!--	<div class="popupBottom">
							<h1 style="text-align:center; ">*For Existing Users <a href="#" id="show_login"> Login</a></h1>
							</div>-->
						<?php } ?>                     
					</div>
				</div>          
        </div>
      </div>
    </div>
  </div>
  