  <footer id="footer">
    <section class="footersection1">
      <div class="layout">
       <?php echo $this->getChildHtml('footer_toplinks') ?>
      </div>
    </section>
    <section class="footersection2">
      <div class="layout">
        <div class="f-colm">      
        <?php echo $this->getChildHtml('footer_about_us') ?>
		</div>
        <div class="f-colm">
         <?php echo $this->getChildHtml('footer_customer') ?>
        </div>
        <div class="f-colm">
         <?php echo $this->getChildHtml('footer_account') ?> 
        </div>
        <div class="f-colm">
		 <h3>Products</h3>
		<ul class="links">
			<?php $_helper = Mage::helper('catalog/category');
			$_categories = $_helper->getStoreCategories();
			if (count($_categories) > 0): ?>
			<?php foreach($_categories as $_category): ?>
			<li>
			<a href="<?php echo $_helper->getCategoryUrl($_category) ?>">
			<?php echo $_category->getName() ?>
			</a>
			</li>
			<?php endforeach; ?>
			<?php endif; ?>
			<li><a href="#">Great Gifts</a></li>
			<li><a href="<?php echo Mage::getBaseUrl(); ?>testimonial">Testimonial</a></li>
		</ul>
		 <?php //echo $this->getChildHtml('footer_products') ?> 
        </div>
        <div class="f-colm">
          <?php echo $this->getChildHtml('footer_corporate') ?> 
		 </div>
        <div class="f-colm social-colm">
          <?php echo $this->getChildHtml('footer_social') ?> 
        </div>        
        <p><?php echo $this->getCopyright() ?></p>
      </div>
    </section>
    <section class="secureSec">
      <div class="layout">      
        <div class="secureShop">
          <h4>Secure shopping :</h4>
          <figure><img src="<?php echo $this->getSkinUrl('images/secure_Img.jpg') ?>" alt="" /></figure>
        </div>
        <div class="paymentSec">
          <h4>Payment options :</h4>
          <figure><img src="<?php echo $this->getSkinUrl('images/payimg.png') ?>" alt="" /></figure>
        </div>
        <div class="shippingSec">
          <h4>Shipping Partners :</h4>
          <figure><img src="<?php echo $this->getSkinUrl('images/shipping.png') ?>" alt="" /></figure>
        </div>        
      </div>
    </section>
    <section class="productSec">
      <div class="layout">
	        <?php echo $this->getChildHtml('footer_products_info') ?>

              </div>
    </section>
  </footer>
  