<script type="text/javascript">
jQuery(document).ready(function(){
               		jQuery("#inTouch").validate({
                rules: {
                    email_id: {
                        required: true,
						email:true
                    },
					 mobile_no: {
                        required: true,
                        number: true
                    },
					 address: {
                        required: true
                    }
                },
                messages: {
				 email_id: {
                        required: "Email required",
                    },
					mobile_no: {
                        required: "Mobile No. of is required",
                    },
					address: {
                        required: "Address is required",
                    }
				},
				highlight: function(element) {
	               jQuery(element).addClass("error");
	         },
	         unhighlight: function(element) {
	           
	               jQuery(element).removeClass("error");
	         },
	         errorPlacement: function(error, element) {
	            
	               error.insertAfter(element);
	           
	         },
                submitHandler: function(form) {
                    jQuery.ajax({
                        type: "POST",
                        url: "<?php echo $this->getUrl('form-simplecontact/') ?>index/inTouch",
                        data: jQuery(form).serialize(),
                        cache: false,
                        success: function(result) 
						{
                            if (result == '1')
							{
								jQuery("#inTouch")[0].reset();
								jQuery('#error').hide();
                                jQuery("#success").show().delay(5000).fadeOut();
							}
							else
							{
								jQuery("#inTouch")[0].reset();
								jQuery("#error").show().delay(5000).fadeOut();
								jQuery('#success').hide();
							} 
						}
                    });
                    return false;
                }
            });
 //Enquiry form validation ends 			
        });
</script>

<div class="footerStripWrap">
    <div class="footerStripTop">
      <div class="layout">        
        <ul class="stripLinks">
          <li class="first"><a href="#strip1"><span>Find a store</span></a></li>
          <li class="second"><a href="#strip2"><span>Recently viewed</span></a></li>
          <li class="third"><a href="#strip3"><span>Track Order</span></a></li>
          <li class="fourth"><a href="#strip4"><span>Top Offers</span></a></li>
           <li class="seven"><a href="#strip7"><span>My Wishlist</span></a></li>
          <li class="fifth"><a href="#strip5"><span>Be in Touch</span></a></li>
          <li class="sixth"><a href="#"><span>Live Chat</span></a></li>
        </ul>
        <a class="downArrow" href="#"></a>        
      </div>
    </div>
    <div class="footerStripBottom">
      <div class="layout">
        <div class="stripContent" id="strip1">
          <div class="recentlyViewed">
            <em class="shadow-hide"></em>           
			<?php 
			echo "Hello";
			?>           
          </div>          
        </div>

	  
        <div class="stripContent" id="strip2">
          <div class="recentlyViewed">
            <em class="shadow-hide"></em>
            <div id="recentViewedList">
			<?php 
			echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/recently_viewed.phtml')->toHtml();
			?>
            </div>
          </div>          
        </div>
        <div class="stripContent" id="strip3">
          <div class="trackOrder">
            <h4>Please enter your order number below.</h4>
            <p>To check your order number, refer to your email confirmation or the order history in your account.</p>
            <div class="trackField">
              <input type="text" name="" value="Enter your order number here...">
              <input type="submit" name="" value="track order">
            </div>
            <p>In case any further queries, please call us on xxxx xxx xxxx, International Users: +91-20-46608100 (From 10AM to 7PM India Time)</p>
          </div>
        </div>
        <div class="stripContent" id="strip4">
          <div class="topOffers">
            <em class="shadow-hide"></em>
            <div id="topOffers">
              <div class="item">
                <a href="#"><img src="<?php echo $this->getSkinUrl('images/top-offer1.jpg') ?>" alt="" /></a>
              </div>
              <div class="item">
                <a href="#"><img src="<?php echo $this->getSkinUrl('images/top-offer2.jpg') ?>" alt="" /></a>
              </div>
              <div class="item">
                <a href="#"><img src="<?php echo $this->getSkinUrl('images/top-offer2.jpg') ?>" alt="" /></a>
              </div>              
            </div>
          </div>
        </div>
        <div class="stripContent" id="strip5">
          <div class="beInTouch">
            <div class="beInTouchLeft">
              <h4>YOUR QUERY IS VALUABLE TO US</h4>
			  <div id="error" style="display:none">
			  Error 
			  </div>
			   <div id="success" style="display:none">
			  Success 
			  </div>
			  <form id="inTouch" name="inTouch">
              <ul class="touchrow">
                <li>
                  <input type="text" name="email_id" value="Email ID" id="email_id">                  
                </li>
                <li>
                  <input type="text" name="mobile_no" value="Mobile" id="mobile_no" >
                </li>
                <li>
                  <textarea name="address" cols="0" rows="5" id="address">Feedback</textarea>
                </li>
                <li>
                  <input type="submit" name="" value="Submit">
                </li>
              </ul>
			  </form>
            </div>
            <div class="beInTouchRight">
              <ul class="touchrow">
                <li>
                  <h4>Call us</h4>
                  <p>18001039825 (Toll Free), +91-120-4299700, +91-9910409734</p>
                </li>
                <li>
                  <h4>Email</h4>
                  <p><a href="#">contact@biotique.com</a></p>
                </li>
                <li>
                  <h4>Address</h4>
                  <p>Bio Veda Action Research Co. Corporate Headquarters <span>D-105,Phase 2 Noida-201305 </span>
                   <span>Fax: 91-120-4352535</span></p> 
                </li>
              </ul>
              <ul class="socialConnect">
                <li>connect with us</li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
		<div class="stripContent" id="strip7">
		<div class="recentlyViewed">
					<em class="shadow-hide"></em>
					<div id="wishList">
						<?php	$customer = Mage::getSingleton('customer/session')->getCustomer();
						if ($customer->getId())
						{
						$wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true);
						$wishListItemCollection = $wishlist->getItemCollection(); 
							foreach ($wishListItemCollection as $item)
							{
							$Products_one = Mage::getModel('catalog/product')->load($item->getProductId());
							?>
							<div class="item">
								<div class="probox">
									<div class="proImg">
										<?php  if ($item->getId())
										{ ?>
										<figure><img src="<?php echo $Products_one->getImageUrl(); ?>" alt=""></figure>
										<?php 
										} ?>                 
									</div>
									<div class="proContent">
									<!-- <span class="top-hd">Top Seller</span> -->
									<h4><?php echo $item->getName() ?></h4>
									<p>  <?php echo ($this->escapeHtml($item->getDescription() ? $item->getDescription() : 'Empty')) ?>
									Hydrating Foaming Face Wash</p>                      
										<div class="review">
											<div class="star">
											<span style="width:60%;"></span>
											</div>
											<span class="review-text">(13 reviews)</span>
										</div>
									<h5>INR <?php echo $item->getPrice(); ?></h5>
									<a href="<?php echo $this->getProductUrl($_item) ?>" class="ctn">shop now</a> 
									</div>
								</div>
							</div>
							<?php 
							} 
						} ?>                     
					</div>
				</div>          
        </div>
      </div>
    </div>
  </div>