  <?php $qty=$this->helper('checkout/cart')->getSummaryCount(); ?>  
  <div class="cd-panel from-left">
    <div class="cd-panel-header">
      <figure><a href="#"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="" /></a></figure>
      <a href="#0" class="cd-panel-close"><i class="fa fa-times"></i></a>
    </div>
    <div class="cd-panel-container">
      <div class="cd-panel-content">
          <div class="shopbysection">
            <h3>Shop by section</h3>
            <div id="mobileNav"></div>
            <h3>Quick links</h3>
            <ul class="mobileQuickLink">
			  <li class="first"><a href="<?php echo Mage::getUrl("storelocator");?>"><span>Find a store</span></a></li>
			  <li class="second"><a href="<?php echo Mage::getUrl("recently-viewed-products");?>"><span>Recently viewed</span></a></li>
			  <li class="third"><a href="<?php echo Mage::getUrl("trackorder");?>"><span>Track Order</span></a></li>
			  <li class="fourth"><a href="<?php echo Mage::getUrl("top-offers");?>"><span>Top Offers</span></a></li>
			  <li class=""><a href="<?php echo Mage::getUrl("contact-us");?>"><span>Be in Touch</span></a></li>
            </ul>
          </div>
      </div>
    </div>
  </div>

  <header id="header">
    <div class="layout">      
      <div class="logoBlock">
        <figure><a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" alt="" /></a></figure>
      </div>
      <div class="topRight">
        <ul class="toplinks">
          <!--<li><a href="#" id="e-signup"><i class="fa fa-plus"></i> Free Shipping and Samples*</a></li>-->
          <li><?php // echo $this->getChildHtml('customer_form_login2'); ?></li>
        <?php if(Mage::getSingleton('customer/session')->isLoggedIn()): 
                $customer = Mage::getSingleton('customer/session')->getCustomer();
        ?>
          <li><a href="#" id="account"><i class="fa fa-plus"></i><?php echo "Welcome, ".$customer->getFirstname(); ?></a>
            <div class="accountWrap">
              <ul class="accountList">
                <li><a href="<?php echo $this->getUrl('customer/account/') ?>">My Account</a></li>
                <li><a href="<?php echo $this->getUrl('') ?>wishlist">My Wishlist</a></li>
                <li><a href="<?php echo $this->getUrl('checkout/cart') ?>">My Cart</a></li>
				<li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">Log Out</a></li>
              <!--   <li><a href="#">Checkout</a></li> 
                <li><a href="#">Register</a></li>
                <li><a href="#">Log In</a></li> -->
              </ul>
            </div>
          </li>
        <?php else: ?>
            <li><a href="#" class="e-login2"><i class="fa fa-plus"></i> LOGIN</a></li>
            <li><a href="#" class="e-account" id="account"><i class="fa fa-plus"></i> Register</a></li>
        <?php endif; ?>   
          <li class="fb"><a target="_blank" href="https://www.facebook.com/Biotique"><i class="fa fa-facebook"></i></a></li>
          <li class="twitter"><a target="_blank" href="https://twitter.com/biotique_world"><i class="fa fa-twitter"></i></a></li>
          <li class="blog"><a target="_blank" href="https://in.pinterest.com/biotique/"><i class="fa fa-pinterest-p"></i></a></li>
        </ul>
      </div>      
    </div>
  </header>

  <div id="navbar">
    <div class="layout">
      <div class="hamburgMenu">
          <button type="button" class="cd-btn">            
              <span></span>
              <span></span>
              <span></span>
          </button>              
      </div>
      <?php echo $this->getChildHtml('topMenu') ?>
      <ul class="rightIcon">
        <li id="m-offer"><a href="#"></a></li>
        <li id="m-chat"><a href="#"></a></li>
        <li><a href="#" id="fa-search"><i class="fa fa-search"></i></a>
          <?php echo $this->getChildHtml('topSearch') ?>
        </li>
        <?php /*<li><?php if($qty){?><a href="<?php echo Mage::getBaseUrl(); ?>checkout/cart"><i class="fa fa-lock"></i></a>
		<?php } else {?>
		<a href="#" id="faLock"><i class="fa fa-lock"></i></a>
          <div class="cartBlock">
            <a href="#" class="cartCtn"><i class="fa fa-times"></i></a>
            <h5><a href="#">RECENTLY ADDED ITEM(S)</a></h5>
			
            <span>You have <?php echo ($qty > '0' ) ? $qty :'no' ?>  items in your shopping cart.</span>
          </div>
		<?php } ?>
        </li> */ ?>
        <li><?php if($qty){?><a href="<?php echo Mage::getBaseUrl(); ?>checkout/cart"><i class="fa fa-lock"></i>
		<!--Added by A on 18-02-2016 for Cart Count bubble -->
			<span class="icon-cart-count">
				<?php
				  $count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
				  echo $this->__('%s',$count);
				  
				?>
			</span>
			<!-- END CART Count bubble--></a>
		<?php } else {?>
		<a href="#" id="faLock" class="icon-cart-header"><i class="fa fa-lock"></i>
			<!--Added by A on 18-02-2016 for Cart Count bubble -->
			<span class="icon-cart-count">0</span>
			<!-- END CART Count bubble-->
		  </a>
          <div class="cartBlock">
			<a href="#" class="cartCtn"><i class="fa fa-times"></i></a>
            <h5><a href="#">RECENTLY ADDED ITEM(S)</a></h5>
			
            <span>You have <?php echo ($qty > '0' ) ? $qty :'no' ?>  items in your shopping cart.</span>
          </div>
		<?php } ?>
        </li>

      </ul>
    </div>
  </div>
  <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?> 
   <?php echo $this->getChildHtml('custom_currency_selector') ?>
<?php //echo $this->getLayout()->createBlock('directory/currency')->setTemplate('directory/currency.phtml')->toHtml(); ?>

<?php /*
$currencyBlock = Mage::app()->getLayout()->createBlock('directory/currency');

if($currencyBlock->getCurrencyCount() > 1): ?>
<div class="form-language">
    <label for="custom-currency-selector"><?php echo $this->__('Your Currency:') ?></label>
    <select onchange="window.location.href=this.value" name="custom-currency-selector" id="custom-currency-selector">
        <?php foreach ($currencyBlock->getCurrencies() as $_code => $_name): ?>
        <option value="<?php echo $currencyBlock->getSwitchCurrencyUrl($_code)?>"
            <?php if($_code == $currencyBlock->getCurrentCurrencyCode()): ?>
                selected="SELECTED"
            <?php endif; ?>>
            <?php echo $_code ?>
        </option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; */ ?> 

   <!-- INCRDENTS POPUP CONTENT -->
  <div class="popupcontent" style="display:none">
     <div class="customPopup">
        <a class="closeCtn" onclick="closepopup()" href="#"><i class="fa fa-times"></i></a>      
        <div class="">
           <div class="popupTop">
              <h5>Ingredients</h5>
           </div>
           <div class="popupMiddleContent"> 

           </div>
        </div>      
     </div>
  </div>
  <script type="text/javascript">
  function closepopup(){
    jQuery(".popupcontent").hide();
    jQuery(".overlay").hide();
  }
  </script>
<!-- INCRDENTS POPUP CONTENT -->

