<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
//$category_id = Mage::registry('current_category')->getId();
$category_id = '';
$category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
?>
<div class="tabContainer">
<?php if($_additional = $this->getAdditionalData()):
	foreach ($_additional as $_data){
		$lbl = $this->escapeHtml($this->__($_data['label']));
	    $detail[$lbl] = $_helper->productAttribute($_product, $_data['value'], $_data['code']);
	}
?>
    <ul <?php if($category_id == 116 || $category_id == 141){?>  class="tabs_P" <?php } else { ?>  class="tabs" <?php }?>>
        <li><a href="#des"><span></span> Description </a></li>
        <li><a href="#ingr"><span></span> Ingredients </a></li>
        <li><a href="#how"><span></span> How to use </a></li>
    </ul>
    <div id="des" class="tabCont">
    	<p><?php echo $detail['Description']; ?></p>
    </div>
    <div id="ingr" class="tabCont">
    	<p><?php echo $detail['ingredients']; ?></p>
    </div>
    <div id="how" class="tabCont">
    	<p><?php echo $detail['How To Use']; ?></p>
    </div>
<?php endif; ?>
</div>