<div id="registerPopup">


   <div class="customPopup">
      <a href="#" class="closeCtn"><i class="fa fa-times"></i></a>
      <div class="popupTop">
         <h5>Welcome to Biotique</h5>
      </div>
      <div class="popupMiddle">
         <div class="popupLeft">
            <h4>Register</h4>
		<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.login.extra')?>	
			
			
			 <ul class="popupinputRow">
			    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <ul class="form-list">
                
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
				
				
                <li>
                     <!-- <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label> -->
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" placeholder="Email Address" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>

                <?php //if ($this->isNewsletterEnabled()): ?>
               <!-- <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php //echo $this->getChildHtml('customer.form.register.newsletter')?>
                </li> -->
                <?php //endif ?> 
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
		
            	<?php
				$var_attrs = array(); // will be used in JS
				$model = 'customer/attribute_collection'; 
				$type='customer'; 
				$collection = Mage::getResourceModel($model)  
				->setEntityTypeFilter( Mage::getModel('eav/entity')->setType($type)->getTypeId() )  
				->addVisibleFilter()
				->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC'); 
				
				foreach($collection as $attribute) {
					$attr = $attribute->toArray();

					if($attr['is_required'])
						$var_attrs[] = $attr['attribute_code'];

					//echo '<li>';
					$func = 'get'.  str_replace(' ', '',  ucwords(str_replace('_', ' ', $attr['attribute_code'])) );

//call_user_func(array(get_class($this->getFormData()), $func));
					//echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__( $attr['frontend_label'] ) . '</label>';
					switch($attr['frontend_input']) {
						case 'text':
							echo '
							<div class="input-box">
							<li>
								<input type="text" placeholder="'.$attr['frontend_label'].'" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text" /></li>
							</div>';
							break;
						
						case 'select':
							echo '
							<div class="input-box">';
							echo '<select name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'"  >';
							foreach ($attribute->getSource()->getAllOptions(true, true) as $instance) {
								  echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape($this->getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
							}
							echo '</select>';

							echo '
							</div>';							
							break;

						case 'textarea':
							echo '
							<div class="input-box">
								<textarea name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" >'. $this->htmlEscape($this->getFormData()->$func()) .'</textarea>
							</div>';
							break;

						case 'multiselect':
							echo '
							<div class="input-box">';
							echo '<select name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" multiple="multiple" >';
							foreach ($attribute->getSource()->getAllOptions(true, true) as $instance) {
								  echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape($this->getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
							}
							echo '</select>';
							break;
							
						case 'date':
							echo '
							<div class="input-box">
								<input type="text" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text" style="width:110px !important;" />
								<img style="" title="'. $this->__('Select Date') .'" id="'.$attr['attribute_code'].'_trig" class="v-middle" alt="" src="'. $this->getSkinUrl('images/grid-cal.gif') .'">
							</div>';
							echo '<script type="text/javascript">
									Calendar.setup({
										inputField : "'.$attr['attribute_code'].'",
										ifFormat : "'. Varien_Date::convertZendToStrFtime(Mage::app()->getLocale()->getDateFormatWithLongYear(), true, false) .'", 
										button : "'.$attr['attribute_code'].'_trig",
										showsTime: false,
										align : "Bl",
										singleClick : true
									});
								</script>';
							break;
					}
					
					echo '
						</li>';
				}
				?>
		
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset ">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <div class="input-box">
                            <input type="password" name="password" id="password" placeholder="Password" class="input-text required-entry validate-password" style="margin-bottom:10px" />
                        </div> 
                    </div>
                    <div class="field">
                        <div class="input-box">
                            <input type="password" name="confirmation" placeholder="Confirm Password" id="confirmation" class="input-text required-entry validate-cpassword" style="margin-bottom:10px" />
                        </div>
                    </div> 
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>
        
        <?php //echo $this->getChildHtml('inchoo_socialconnect_register'); ?>
        
       <!-- <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p> -->
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
       <!-- </div> -->
    </form>
	</ul>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
			
			
	
         </div>
         <div class="popupRight">
            <h4>Why Register?</h4>
            <ul class="popupList">
               <li><i class="fa fa-caret-right"></i>	Faster Checkout</li>
               <li><i class="fa fa-caret-right"></i>	Store multiple shipping addresses</li>
               <li><i class="fa fa-caret-right"></i>View and track your orders </li>
            </ul>
            <div class="popupOfferproduct">
               <div class="popupOfferImg">
                  <figure><img src="<?php echo $this->getSkinUrl('images/popupOfferImg.png') ?>" alt="" /></figure>
               </div>
               <!--<div class="popupOfferContent">
                  <strong>20% off</strong>
                  <small>Bio Cucumber</small>
                  <span>PORE TIGHTENING TONER WITH HIMALAYAN WATERS</span>
                  <a href="#" class="ctn">Shop Now</a>
               </div>-->
            </div>
         </div>
      </div>
      <div class="popupBottom">
         <h3>for existing users <a href="#" id="show_login">Login</a></h3>
      </div>
   </div>
</div>


