<?php 

if($this->canShowBlock()): ?>
        <?php echo $this->getStateHtml() ?>
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
          <?php $_filters = $this->getFilters();
          
          $filt_pos = array();
          foreach ($_filters as $_filter):
              if(in_array($_filter->getName(), array('Category', 'Collection', 'Concern'))){
                switch ($_filter->getName()) {
                  case 'Collection': $filt_pos['a'] = $_filter; break;
                  case 'Category': $filt_pos['b'] = $_filter; break;
                  case 'Concern': $filt_pos['c'] = $_filter; break;
                  default: break;
                }
              }
          endforeach;
          ksort($filt_pos);
          ?>

          <?php 
          foreach ($filt_pos as $_filter):
            if($_filter->getItemsCount()): ?>
              <div class="leftrow">
                <h4>By <?php echo $this->__($_filter->getName()) ?></h4>
                <?php echo $_filter->getHtml() ?>
              </div>
            <?php endif; ?>
          <?php endforeach; ?>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
<?php endif; ?>

<!--
<div class="leftrow">
  <h4>By Concerns</h4>
  <ul class="leftrowList">
    <li>
      <input type="checkbox" class="styled" name="" value="" id="1">
      <label for="1">Dryness</label>
    </li>
    <li>
      <input type="checkbox" class="styled" name="" value="" id="2">
      <label for="2">Aging</label>
    </li>
    <li>
      <input type="checkbox" class="styled" name="" value="" id="3">
      <label for="3">Oily & Acne</label>
    </li>
    <li>
      <input type="checkbox" class="styled" name="" value="" id="4">
      <label for="4">Uneven Skin Tone</label>
    </li>
    <li>
      <input type="checkbox" class="styled" name="" value="" id="5">
      <label for="5">Prevention & Protection</label>
    </li>
    <li>
      <input type="checkbox" class="styled" name="" value="" id="6">
      <label for="6">Dull Skin Tone</label>
    </li>
  </ul>
</div> -->