<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php echo $this->getToolbarHtml() ?>
    <div class="productWrap">
    <?php $_collectionSize = $_productCollection->count();
        $_columnCount = $this->getColumnCount(); 
        $i=0; foreach ($_productCollection as $_product): ?>
        <?php 
            $_productNameStripped = $this->stripTags($_product->getName(), null, true); 
        ?>
        <?php if($i%2 == 0): ?>
          <div class="productRow">
            <ul class="productBox">
        <?php endif; ?>
          <li <?php echo $i%2 != 0 ? ' class="last"':''; ?>>
            <div class="probox">
              <div class="proImg">
                <figure><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></figure>
              </div>
              <div class="proContent">
                <h4><?php echo $_productNameStripped; ?></h4>
                <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                <small>Best for For All Skin Types</small>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                 
                <h5><?php echo $this->getPriceHtml($_product, true) ?></h5>
                <?php if($_product->isSaleable()): ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" class="shop-ctn"><i class="fa fa-shopping-cart"></i>shop now</a>
                <?php else: ?>
                    <a href="javascript:void(0)" title="<?php echo $this->__('Out of stock') ?>" class="shop-ctn"><i class="fa fa-shopping-cart"></i><?php echo $this->__('Out of stock') ?></a>
                <?php endif; ?>
            </div>
          </li>
        <?php if($i+1 == sizeof($_productCollection) && $i%2 == 0){ ?>
            <li class="last"></li>
        <?php } ?>

        <?php if($i%2 != 0): ?>
            </ul>
          </div>
        <?php endif; $i++; ?>
    <?php endforeach ?>
    </div>
<?php endif; ?>