<div id="sidebar">
  <div class="sidebarHd">
     <h3>Shop by<em></em></h3>
  </div>
  <?php 
  if($this->canShowBlock()): ?>
          <?php echo $this->getStateHtml() ?>
          <?php if ($this->getLayer()->getState()->getFilters()): ?>
              <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php //echo $this->__('Clear All') ?></a></div>
          <?php endif; ?>
          <?php if($this->canShowOptions()): ?>
            <?php $_filters = $this->getFilters();
            
            $filt_pos = array();
            foreach ($_filters as $_filter):
                if(in_array($_filter->getName(), array('Category', 'Collection', 'Concern', 'Ingredient'))){
                  switch ($_filter->getName()) {
                    case 'Collection': $filt_pos['a'] = $_filter; break;
                    case 'Category': $filt_pos['b'] = $_filter; break;
                    case 'Concern': $filt_pos['c'] = $_filter; break;
                    case 'Ingredient': $filt_pos['d'] = $_filter; break;
                    default: break;
                  }
                }
            endforeach;
            ksort($filt_pos);
            foreach ($filt_pos as $_filter):
              if($_filter->getItemsCount()): ?>
                <div class="leftrow">
                  <h4>By <?php echo $this->__($_filter->getName()) ?></h4>
                  <?php echo $_filter->getHtml() ?>
                </div>
              <?php endif; ?>
            <?php endforeach; ?>
              <script type="text/javascript">decorateDataList('narrow-by-list')</script>
          <?php endif; ?>
  <?php endif; ?>
<div class="leftrow">
<h4>By category</h4>
<ul class="concernsList ">
<?php 
$parentId = Mage::registry('current_category')->getParentCategory()->getId();
$cats = Mage::getModel('catalog/category')->load($parentId)->getChildrenCategories();
    foreach ($cats as $cat)
    {
        if ($cat->getId() == Mage::registry('current_category')->getId())
        {
        echo  "<li class='selected'><a href='".$cat->getUrl()."'>".$cat->getName()."</a></li> ";
        }
        else
        {
        echo  "<li><a href='".$cat->getUrl()."'>".$cat->getName()."</a></li> ";
        }
    // then do something with $cat
    }
?>
</ul>
</div>
</div>