<div class="shoppingbagContainer">
   <ul class="shoppingBag">
      <li><a href="<?php echo Mage::getUrl("checkout/cart"); ?>"><span class="sCircle active">1</span><span class="shoppingText activeText">Shopping Bag</span></a></li>
	  <li><span class="sCircle">2</span><span class="shoppingText">Billing & Shipping Address </span></li>
      <li><span class="sCircle">3</span><span class="shoppingText">Payment Details </span></li>
      <li><span class="sCircle">4</span><span class="shoppingText">Place  Order</span></li>
   </ul>
   <span class="shoppingShadow"></span>
</div>
