<div class="newCollection">
   <div class="collectionTop">
      <div class="wrapper">
         <div class="block">
            <h1>our new collection</h1>
         </div>
      </div>
      <em class="shape"></em>
   </div>
   <div class="collectionBottom">
      <em class="shadow"></em>
      <div class="wrapper">
         <div class="block">
            <div class="collectionImg">
               <figure><img src="<?php echo $this->getSkinUrl('images/collectionImg.jpg'); ?>" alt="" /></figure>
            </div>
            <div class="collectionCon">
               <div class="collectionLeft">
                  <figure><img src="<?php echo $this->getSkinUrl('images/biotique.png'); ?>" alt="" /></figure>
               </div>
               <div class="collectionRight">
                  <h2>A window to our exclusive luxury collection</h2>
                  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam.</p>
                  <a href="#" class="ctnBtn">View collection</a> <a href="#" class="ctnBtn">why Biotique advance?</a> 
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="bestSellers">
   <em class="shadow"></em>
   <div class="bestSellersbg">
      <figure><img src="<?php echo $this->getSkinUrl('images/sellers.jpg'); ?>" alt="" /></figure>
   </div>
   <div class="bestSellerscon">
      <div class="wrapper">
         <div class="block">
            <div class="sellersContent">
               <h3>best sellers</h3>
               <p>Go head over heels with our 10 most beloved formulations chosen by our customers</p>
            </div>
            <div class="sellersSlider">
               <div id="bestseller" class="sky-carousel">
                  <div class="sky-carousel-wrapper">
                     <ul class="sky-carousel-container">
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl1img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl2img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel 2</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl3img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel 3</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl4img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel 4</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl5img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel 5</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                        <li>
                           <img src="<?php echo $this->getSkinUrl('images/seller2.png'); ?>" alt="" /> <a href="javascript:;" id="sl6img" class="bigImg fancybox"></a>
                           <div class="sc-content">
                              <h2>Bio honey gel 6</h2>
                              <p>INR 199.00</p>
                           </div>
                        </li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="product-feature">
   <section class="wrapper">
      <div class="pf-wrap">
         <article class="product-left">
            <figure> <img src="<?php echo $this->getSkinUrl('images/girl_pic.png'); ?>" alt="" title=""> </figure>
            <section class="prod-desc">
               <h2>SKIN CONSULTATION</h2>
               <h5>FIND THE BEST SOLUTIONS</h5>
               <p>Learn more about your skin type and the products that are perfect for you with our Skincare Consultation</p>
               <a href="#">FIND MORE</a> 
            </section>
         </article>
         <article class="product-right">
            <div class="prBox">
               <div class="flexslider" id="flexslider2">
                  <ul class="slides">
                     <li> <img src="<?php echo $this->getSkinUrl('images/coconut.png'); ?>" alt="" title=""> <strong>COCONUT</strong> <a href="#" class="read-more">Read More</a> </li>
                     <li> <img src="<?php echo $this->getSkinUrl('images/coconut.png'); ?>" alt="" title=""> <strong>COCONUT</strong> <a href="#" class="read-more">Read More</a> </li>
                     <li> <img src="<?php echo $this->getSkinUrl('images/coconut.png'); ?>" alt="" title=""> <strong>COCONUT</strong> <a href="#" class="read-more">Read More</a> </li>
                  </ul>
               </div>
            </div>
            <section class="prod-desc">
               <h2>INGREDIENTS</h2>
               <h5>TAKE THE NATURAL PATH</h5>
               <p>Biotique blends the powers of Ayurvedic healing wisdom</p>
               <a href="#">FIND ALL</a> 
            </section>
         </article>
      </div>
   </section>
</div>