<!DOCTYPE html>
	<html lang="en">
			<head>
				<?php echo $this->getChildHtml('head') ?>
<script>var $j = jQuery.noConflict();</script>
			</head>
			<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':''?>>
				<?php echo $this->getChildHtml('after_body_start') ?>
				<?php echo $this->getChildHtml('header') ?>
				<?php echo $this->getChildHtml('breadcrumbs') ?>
				<?php echo $this->getBlockHtml('beforecontainer') ?>

				<?php if( Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' && Mage::getSingleton('cms/page')->getIdentifier() == 'home') : 

                    echo $this->getChildHtml('global_messages');
					echo $this->getChildHtml('content');
				?>
				<?php else:  
					$curr_uri = trim(Mage::app()->getRequest()->getRequestUri(), '/');
				?>
					<section class="bodyContainer" <?php if($curr_uri == 'storelocator'){ echo 'id="store-location"';} ?>> 
						<span class="shadow"></span>
						<!-- <div class="layout"> -->

                     		<?php echo $this->getChildHtml('global_messages'); ?>
							<?php echo $this->getChildHtml('content'); ?>
						<!-- </div>  -->
					</section>
				<?php endif; ?>
				<?php echo $this->getChildHtml('footer') ?>
				<?php echo $this->getAbsoluteFooter() ?>
				<?php echo $this->getChildHtml('before_body_end') ?>
			</body>
	</html>