  <section class="innerBanner pc-banner">
    <div class="innerbannerImg">
      <figure><img src="<?php echo $this->getSkinUrl('images/skincare-banner.jpg') ?>" alt="" /></figure>
    </div>
    <div class="innerbannerContent">
      <div class="layout">        
          <div class="productDec">
            <div class="productHeading">
              <h1>Skincare</h1>
            </div>
            <div class="productDetails">
              <div class="pdColm">
                <h3>Collection</h3>
                <ul class="list">
                  <li><a href="#">Biotique Advance</a></li>
                  <li><a href="#">Biotique Botanical</a></li>
                </ul>
              </div>
              <div class="pdColm">
                <h3>Category</h3>
                <ul class="list">
                  <li><a href="#">Cleansing</a></li>
                  <li><a href="#">Exfoliating</a></li>
                  <li><a href="#">Toning</a></li>
                  <li><a href="#">Vitalizing</a></li>
                  <li><a href="#">Moisturizing</a></li>
                  <li><a href="#">Scrubs & Masks</a></li>
                  <li><a href="#">Eye & Lip Care</a></li>
                  <li><a href="#">Sun Care</a></li>
                </ul>
              </div>
              <div class="pdColm">
                <h3>Concerns</h3>
                <ul class="list">
                  <li><a href="#">Dryness</a></li>
                  <li><a href="#">Fairness</a></li>
                  <li><a href="#">Aging</a></li>
                  <li><a href="#">Oily & Acne</a></li>
                  <li><a href="#">Uneven Skin Tone</a></li>
                  <li><a href="#">Prevention & Protection</a></li>
                  <li><a href="#">Dull Skin</a></li>
                </ul>
              </div>
            </div>
          </div>
      </div>
    </div>
  </section>

  <section class="bodyContainer"> 
    <span class="shadow"></span>
    <div class="pc-bestSeller">
      <div class="layout">
        <div class="block">
          <div class="bestsellerColm">
            <h2>best sellers</h2>
            <div class="slidercolm">
              <ul class="bestsellerSlider">
                  <li>
                      <div class="bs-productBox">
                        <figure><img src="<?php echo $this->getSkinUrl('images/bs-pro-02.jpg') ?>" alt="" title=""></figure>
                        <div class="productSlider-con">
                          <h4>COCONUT</h4>
                          <span>INR 199.00</span>
                          <a href="#" class="ctn">Shop Now</a>
                        </div>
                      </div>
                  </li>
                  <li>
                    <div class="bs-productBox">
                      <figure><img src="<?php echo $this->getSkinUrl('images/bs-pro-01.jpg') ?>" alt="" title=""></figure>
                      <div class="productSlider-con">
                        <h4>COCONUT</h4>
                        <span>INR 199.00</span>
                        <a href="#" class="ctn">Shop Now</a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="bs-productBox">
                      <figure><img src="<?php echo $this->getSkinUrl('images/bs-pro-01.jpg') ?>" alt="" title=""></figure>
                      <div class="productSlider-con">
                        <h4>COCONUT</h4>
                        <span>INR 199.00</span>
                        <a href="#" class="ctn">Shop Now</a>
                      </div>
                    </div>
                  </li>
                  <li>
                    <div class="bs-productBox">
                      <figure><img src="<?php echo $this->getSkinUrl('images/bs-pro-02.jpg') ?>" alt="" title=""></figure>
                      <div class="productSlider-con">
                        <h4>COCONUT</h4>
                        <span>INR 199.00</span>
                        <a href="#" class="ctn">Shop Now</a>
                      </div>
                    </div>
                  </li>
              </ul>
            </div>
          </div>
          <div class="specialofferColm">
            <h2>Special OFFERS</h2>
            <div class="slidercolm">
              <ul class="productSlider">
                <li>
                  <div class="bs-offerbox">
                    <figure>
                        <img src="<?php echo $this->getSkinUrl('images/bs-pro-03.jpg') ?>" alt="" title="">
                    </figure>
                    <div class="bs-offer-text">
                      <h5>BIO WHITE ADVANCED FAIRNESS KIT</h5>
                      <small>For a Radiant Fair Glow</small>
                      <p>Set of 6 Product for Radiant Fair Glow</p>
                      <strong> INR 1,599.00</strong>
                      <a href="#" class="ctn">Shop Now</a>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="bs-offerbox">
                    <figure>
                        <img src="<?php echo $this->getSkinUrl('images/bs-pro-03.jpg') ?>" alt="" title="">
                    </figure>
                    <div class="bs-offer-text">
                      <h5>BIO WHITE ADVANCED FAIRNESS KIT</h5>
                      <small>For a Radiant Fair Glow</small>
                      <p>Set of 6 Product for Radiant Fair Glow</p>
                      <strong> INR 1,599.00</strong>
                      <a href="#" class="ctn">Shop Now</a>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="defineProduct">
      <span class="shadow"></span>
      <div class="defineProductImg">
        <figure>
            <img src="<?php echo $this->getSkinUrl('images/skincare-banner-2.jpg') ?>" alt="" title="">
        </figure>
      </div>
      <div class="defineProductCon">
        <div class="layout">
          <div class="circlecontent">
            <figure>
                <img src="<?php echo $this->getSkinUrl('images/transparency-circle.png') ?>" alt="" title="">
            </figure>
            <div class="circleText">
              <h4>Skin Consultation</h4>
              <h5>online Skin & Haricare Guide</h5>
              <p>This quick online consultation will help you find targeted solutions to meet your daily, special skin and Haircare needs.</p>
              <span>Answer a few simple questions and receive personalized recommendations designed specifically for you.</span>              
            </div>
            <a href="#" class="get-started">get started</a>
          </div>
        </div>
      </div>
    </div>
  </section> 