<?php
$ingredients = Mage::helper('biotique_ingredients')->fetch_ingredients( $this->getRequest()->getParam('range',''));
?>

<ul class="productSlider"> 
<?php foreach($ingredients as $ingredient): 
         		$prod_name = $ingredient->getAlias();
         	?>
			<li> <a href="<?php echo Mage::getBaseUrl()."products/?item_ingregident=".$ingredient->getData("ingredient_id"); ?>"><img src="<?php echo Mage::getBaseUrl('media') .  'ingredients/'. $ingredient->getData('small_image'); ?>" width="216px" height="180px" alt="" title=""> <strong><?php echo $prod_name; ?></strong></a></li>
			<!--<li> <a href="<?php echo Mage::getBaseUrl()."catalogsearch/result/?q=".$prod_name; ?>"> <img src="<?php echo Mage::getBaseUrl('media') .  'ingredients/'. $ingredient->getData('small_image'); ?>" width="216px" height="180px" alt="" title=""><strong><?php echo $prod_name; ?></strong></a></li>-->

			
		
			<?php endforeach; ?>
			</ul>